### ISSUE TITLE
Hovering over the commit link may trigger an exception

### ISSUE THREAD

**Issue by yuedaregone** [sourcegit-scm/sourcegit#765]
The error's stack trace is as follows:
```
System.ArgumentException: An item with the same key has already been added. Key: 3860c9c6a47ee6d80e30577d7eedc29a1fb4fb1c
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at SourceGit.Views.CommitMessagePresenter.<>c__DisplayClass15_2.<ProcessHoverCommitLink>b__1() in D:\study\github\sourcegit\src\Views\CommitMessagePresenter.cs:line 299
   at Avalonia.Threading.DispatcherOperation.InvokeCore()
```
I think it may be caused by asynchronous operation in function `ProcessHoverCommitLink`.

**Comment by love-linger** [comment]
Fixed. You can download the latest CI build from Github Action.

**Comment by yuedaregone** [comment]
Thanks!
